language: ruby
before_script:
- export TZ=Europe/Berlin
script:
- "./deploy.sh"
env:
  global:
    - JEKYLL_ENV=production
    - secure: ys1nt5AI2ciYIiZDGCcvpX0UwjMnDqVu2rRHfgYQLjjuMsw25zvV/bHmuFMajqWdBGvIMD/hPxxW5QozdazDqB5aMKkR3MpUb5CUdhV5iIT8oHsL8m80BUWtSshOh0R2PBZx+cTtlqEu3pfwtT+dQhmgKjhFa5DoW8/kIN8tv63AkW3RDa09KBy0d3Q6ANJfrezLKixmOurPBUjIZ7nlbsPeIhxHoIETGHzWV9I86Iv5MAqVzNmlWGKXPpbS80t79ocRkesLOT3+iu6j2uMEbAVDXKMinHcK1OLAf4csAqBTogC4MLtYcGkTn3CFi/EN41zKPSWb8lzDJ+rE0nhQ1Jj/fpIB4+2Lzl2j6nv6/vFUUCRn8RRCxxt9U07z1xC2EbW0TO6V8JM3caMLYsPv8yF3sZxukFpnHO0XraorcoXpINRuYipjueAPVmbv6/CWAeG/bv+zCx4K//lZE8ftEhGVAHzWBTJKfk8nfCGi5r8Km27kfFK9SORcKryYSyFOQzam8tWl6jWEALQ+GGxamFRlpoTV8mX84wjJUMUOpkvYcPHzGzw8IDfvJzLFDJKALJjOe1zMexam4Rnr0oMBTDDESnddecUIc7FxUbm/9qrTsCOu6kfOTmqcbErwxcVWleKlF67DmfYqwDqcyvnmLT1Xyynk/njzOZMPGnvTsvw=
