title: Preslav's Thoughts and Ramblings
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://preslavrachev.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: :year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, amp-jekyll]
paginate: 5
ampdir: amp

sass:
  sass_dir: _sass
  style: compressed

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
