title: Preslav's Thoughts and Ramblings
description: Finding beauty in everyday things.

url: https://preslav.me
baseurl: ""
paginate_path: "/page:num/"
permalink: :year/:month/:day/:title/

#markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, amp-jekyll, jekyll-sitemap]
paginate: 5
ampdir: amp

sass:
  sass_dir: _sass
  style: compressed

navigation:
 - title: Home
   url: /index.html
 - title: Twitter
   url: https://twitter.com/preslavrachev
 - title: GitHub
   url: https://github.com/preslavrachev  
 - title: About
   url: /about-me
 - title: Contact
   url: https://twitter.com/messages/compose?recipient_id=14154587

social:
   github: preslavrachev
   twitter: preslavrachev
   stackoverflow: 1107412/preslavrachev

disqus: preslav

theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: contrast

exclude:
  - "themes"
  - "vendor"

comments:
  provider: "disqus"
  disqus:
    shortname: "preslav"

collections:
  micro:
    output: true
    permalink: /:collection/:path/    

search: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      header:
        overlay_filter: 0.5
        show_overlay_excerpt: false
        overlay_image: https://source.unsplash.com/collection/1922729/1280x400
  # _micro
  - scope:
      path: ""
      type: micro
    values:
      layout: single_micro
      author_profile: true
      share: true
      title: ""    

author:
  name   : "Preslav Rachev"
  avatar : "https://pbs.twimg.com/profile_images/1044556606460100623/ukmK4mgY_400x400.jpg"
  bio    : "A runner and a programming / data science polymath. A Bulgarian living in Germany. Not really your typical 🤓 #machinelearning #cryptocurrency #iosdev #kotlin"
  email  : # optional
  #uri    : "http://your-site.com"
  home   : # null (default), "absolute or relative url to link to author home"

teaser: https://source.unsplash.com/collection/1922729/400x300

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

feed:
  collections:
    micro:
      path: "/micro.xml"    
