title: Preslav's Thoughts and Ramblings
description: Finding beauty in everyday things.

url: https://preslav.me
baseurl: ""
paginate_path: "blog/page:num/"
permalink: :year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, amp-jekyll, jekyll-sitemap]
paginate: 5
ampdir: amp

sass:
  sass_dir: _sass
  style: compressed

navigation:
 - title: Home
   url: /index.html
 - title: Twitter
   url: https://twitter.com/preslavrachev
 - title: GitHub
   url: https://github.com/preslavrachev  
 - title: About
   url: /about-me
 - title: Contact
   url: https://twitter.com/messages/compose?recipient_id=14154587

social:
   github: preslavrachev
   twitter: preslavrachev
   stackoverflow: 1107412/preslavrachev

disqus: preslav

theme: "long-haul"

exclude:
  - "themes"
  - "vendor"
